-- ============================================================
-- A3 骨架資料 — 批次 02：字母 B、C
-- 來源：Cambridge A2 Key / Key for Schools Vocabulary List (Aug 2025)
--
-- 正規化決定（沿用批次 01）：
--   * 斜線條目拆兩筆：cafe/café → cafe；centre/center → 兩筆
--   * 英美對照各建一筆（bookshop / bookstore、chemist / drugstore），
--     variant_of 待全表就位後統一回填
--   * blond(e) 取 blonde；barbecue/barbeque 取 barbecue
--   * PDF 中重複出現的 coat 只建一筆
--   * level_tags 一律 {KET}，YLE 分層待全表完成後統一 UPDATE
-- ============================================================

insert into words
  (headword, pos, zh, level_tags, topics, sense_note, is_phrasal, concreteness, status)
values
-- ---------- B ----------
('baby',            'n',      '嬰兒',                    '{KET}', '{Family and Friends}', null, false, 5, 'active'),
('back',            'n',      '背部；後面',              '{KET}', '{Health, Medicine and Exercise}', null, false, 4, 'active'),
('backpack',        'n',      '後背包',                  '{KET}', '{Clothes and Accessories, Travel and Transport}', null, false, 5, 'active'),
('bad',             'adj',    '壞的、不好的',            '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('badly',           'adv',    '差勁地、嚴重地',          '{KET}', '{}', null, false, 1, 'active'),
('badminton',       'n',      '羽毛球',                  '{KET}', '{Sport}', null, false, 4, 'active'),
('bag',             'n',      '袋子、包包',              '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('bake',            'v',      '烘烤',                    '{KET}', '{Food and Drink}', null, false, 4, 'active'),
('ball',            'n',      '球',                      '{KET}', '{Sport}', null, false, 5, 'active'),
('balloon',         'n',      '氣球',                    '{KET}', '{}', null, false, 5, 'active'),
('banana',          'n',      '香蕉',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('band',            'n',      '樂團',                    '{KET}', '{}', 'The band are on tour this month.', false, 4, 'active'),
('bank',            'n',      '銀行',                    '{KET}', '{Places: Buildings, Services}', 'I changed my money in the bank.（限金融機構，不含河岸）', false, 5, 'active'),
('barbecue',        'n',      '烤肉、烤肉架',            '{KET}', '{Food and Drink, Hobbies and Leisure}', null, false, 5, 'active'),
('baseball',        'n',      '棒球',                    '{KET}', '{Sport}', null, false, 4, 'active'),
('basketball',      'n',      '籃球',                    '{KET}', '{Sport}', null, false, 4, 'active'),
('bat',             'n',      '球棒',                    '{KET}', '{Sport}', 'a baseball bat', false, 5, 'active'),
('bath',            'n',      '洗澡；浴缸',              '{KET}', '{House and Home}', null, false, 4, 'active'),
('bathing suit',    'n',      '泳衣',                    '{KET}', '{Clothes and Accessories, Sport}', null, false, 5, 'active'),
('bathroom',        'n',      '浴室',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('bathtub',         'n',      '浴缸',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('battery',         'n',      '電池',                    '{KET}', '{}', null, false, 5, 'active'),
('be',              'v',      '是、存在',                '{KET}', '{}', null, false, 1, 'active'),
('beach',           'n',      '海灘',                    '{KET}', '{Places: Countryside, The Natural World}', null, false, 5, 'active'),
('bean',            'n',      '豆子',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('bear',            'n',      '熊',                      '{KET}', '{}', null, false, 5, 'active'),
('beard',           'n',      '鬍子',                    '{KET}', '{}', null, false, 5, 'active'),
('beautiful',       'adj',    '美麗的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 2, 'active'),
('because',         'conj',   '因為',                    '{KET}', '{}', null, false, 1, 'active'),
('because of',      'prep',   '由於、因為',              '{KET}', '{}', null, false, 1, 'active'),
('become',          'v',      '變成',                    '{KET}', '{}', null, false, 1, 'active'),
('bed',             'n',      '床',                      '{KET}', '{House and Home}', null, false, 5, 'active'),
('bedroom',         'n',      '臥室',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('bee',             'n',      '蜜蜂',                    '{KET}', '{The Natural World}', null, false, 5, 'active'),
('beetle',          'n',      '甲蟲',                    '{KET}', '{}', null, false, 5, 'active'),
('before',          'prep',   '在……之前',                '{KET}', '{}', null, false, 1, 'active'),
('begin',           'v',      '開始',                    '{KET}', '{}', null, false, 1, 'active'),
('beginner',        'n',      '初學者',                  '{KET}', '{Education}', null, false, 3, 'active'),
('beginning',       'n',      '開始、開頭',              '{KET}', '{}', null, false, 1, 'active'),
('behind',          'prep',   '在……後面',                '{KET}', '{}', null, false, 2, 'active'),
('believe',         'v',      '相信',                    '{KET}', '{}', null, false, 1, 'active'),
('belong',          'v',      '屬於',                    '{KET}', '{}', 'The bag belongs to me.', false, 1, 'active'),
('below',           'prep',   '在……下方',                '{KET}', '{}', null, false, 2, 'active'),
('belt',            'n',      '腰帶',                    '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('beside',          'prep',   '在……旁邊',                '{KET}', '{}', null, false, 2, 'active'),
('best',            'adj',    '最好的',                  '{KET}', '{}', null, false, 1, 'active'),
('better',          'adj',    '更好的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('between',         'prep',   '在……之間',                '{KET}', '{}', null, false, 2, 'active'),
('bicycle',         'n',      '腳踏車',                  '{KET}', '{Hobbies and Leisure, Sport}', null, false, 5, 'active'),
('big',             'adj',    '大的',                    '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 2, 'active'),
('bike',            'n',      '腳踏車',                  '{KET}', '{Hobbies and Leisure, Sport}', null, false, 5, 'active'),
('bill',            'n',      '帳單',                    '{KET}', '{Documents and Texts, Shopping}', 'Can I have my bill, please?', false, 4, 'active'),
('bin',             'n',      '垃圾桶',                  '{KET}', '{House and Home}', 'Can you throw the rubbish in the bin?', false, 5, 'active'),
('biology',         'n',      '生物學',                  '{KET}', '{Education}', null, false, 2, 'active'),
('bird',            'n',      '鳥',                      '{KET}', '{}', null, false, 5, 'active'),
('birth',           'n',      '出生',                    '{KET}', '{}', null, false, 2, 'active'),
('birthday',        'n',      '生日',                    '{KET}', '{Time, Hobbies and Leisure}', null, false, 3, 'active'),
('biscuit',         'n',      '餅乾（英式）',            '{KET}', '{Food and Drink}', 'Br Eng；Am Eng 為 cookie', false, 5, 'active'),
('bit',             'n',      '一點點',                  '{KET}', '{}', 'Just a little bit of cake, please.', false, 1, 'active'),
('black',           'adj',    '黑色的',                  '{KET}', '{Colours}', null, false, 3, 'active'),
('blackboard',      'n',      '黑板',                    '{KET}', '{Education}', null, false, 5, 'active'),
('blanket',         'n',      '毯子',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('block',           'n',      '街區',                    '{KET}', '{Places: Buildings}', 'Shall we walk round the block?', false, 3, 'active'),
('blog',            'n',      '部落格',                  '{KET}', '{Communication and Technology}', null, false, 3, 'active'),
('blonde',          'adj',    '金髮的',                  '{KET}', '{}', null, false, 3, 'active'),
('blood',           'n',      '血',                      '{KET}', '{Health, Medicine and Exercise}', null, false, 5, 'active'),
('blouse',          'n',      '女用襯衫',                '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('blue',            'adj',    '藍色的',                  '{KET}', '{Colours}', null, false, 3, 'active'),
('board',           'n',      '黑板、白板',              '{KET}', '{Education}', 'The teacher is writing on the board.', false, 5, 'active'),
('board game',      'n',      '桌遊',                    '{KET}', '{Entertainment and Media}', null, false, 5, 'active'),
('boat',            'n',      '船',                      '{KET}', '{Sport, Travel and Transport}', null, false, 5, 'active'),
('body',            'n',      '身體',                    '{KET}', '{Health, Medicine and Exercise}', null, false, 5, 'active'),
('boil',            'v',      '煮沸',                    '{KET}', '{Food and Drink}', null, false, 3, 'active'),
('boiled',          'adj',    '水煮的',                  '{KET}', '{Food and Drink}', null, false, 3, 'active'),
('book',            'n',      '書；預訂',                '{KET}', '{Documents and Texts, Education}', 'a good book / book a place on the course', false, 5, 'active'),
('bookcase',        'n',      '書櫃',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('bookshelf',       'n',      '書架',                    '{KET}', '{Education, House and Home}', null, false, 5, 'active'),
('bookshop',        'n',      '書店（英式）',            '{KET}', '{Places: Buildings, Shopping}', 'Br Eng；Am Eng 為 bookstore', false, 5, 'active'),
('bookstore',       'n',      '書店（美式）',            '{KET}', '{Places: Buildings, Shopping}', 'Am Eng；Br Eng 為 bookshop', false, 5, 'active'),
('boot',            'n',      '靴子',                    '{KET}', '{Clothes and Accessories}', 'a pair of boots', false, 5, 'active'),
('bored',           'adj',    '感到無聊的',              '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('boring',          'adj',    '令人無聊的',              '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('born',            'v',      '出生',                    '{KET}', '{}', 'I was born in Manchester.', false, 2, 'active'),
('borrow',          'v',      '借入',                    '{KET}', '{}', 'She borrowed a book from the library.', false, 2, 'active'),
('boss',            'n',      '老闆',                    '{KET}', '{Work and Jobs}', null, false, 4, 'active'),
('both',            'det',    '兩者都',                  '{KET}', '{}', null, false, 1, 'active'),
('bother',          'v',      '打擾',                    '{KET}', '{}', 'Sorry to bother you.', false, 1, 'active'),
('bottle',          'n',      '瓶子',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('bottom',          'n',      '底部',                    '{KET}', '{}', 'at the bottom of the stairs', false, 3, 'active'),
('bowl',            'n',      '碗',                      '{KET}', '{Food and Drink, House and Home}', null, false, 5, 'active'),
('box',             'n',      '盒子、箱子',              '{KET}', '{Food and Drink, House and Home}', null, false, 5, 'active'),
('boy',             'n',      '男孩',                    '{KET}', '{Family and Friends}', null, false, 5, 'active'),
('boyfriend',       'n',      '男朋友',                  '{KET}', '{}', null, false, 4, 'active'),
('bracelet',        'n',      '手鍊',                    '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('brain',           'n',      '大腦',                    '{KET}', '{Health, Medicine and Exercise}', null, false, 5, 'active'),
('brave',           'adj',    '勇敢的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('bread',           'n',      '麵包',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('break',           'v',      '打破；休息',              '{KET}', '{Food and Drink, Work and Jobs}', 'a break for lunch / Someone has broken the window.', false, 3, 'active'),
('break down',      'phr v',  '故障、拋錨',              '{KET}', '{}', 'The car has broken down.', true, 2, 'active'),
('breakfast',       'n',      '早餐',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('bridge',          'n',      '橋',                      '{KET}', '{Places: Town and City, Travel and Transport}', null, false, 5, 'active'),
('bright',          'adj',    '鮮豔的、明亮的',          '{KET}', '{}', 'bright pink（限顏色）', false, 3, 'active'),
('brilliant',       'adj',    '很棒的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', 'I thought the film was brilliant!', false, 1, 'active'),
('bring',           'v',      '帶來',                    '{KET}', '{}', null, false, 2, 'active'),
('bring back',      'phr v',  '帶回來、歸還',            '{KET}', '{}', null, true, 2, 'active'),
('broken',          'adj',    '壞掉的',                  '{KET}', '{}', null, false, 3, 'active'),
('brother',         'n',      '哥哥、弟弟',              '{KET}', '{Family and Friends}', null, false, 4, 'active'),
('brown',           'adj',    '棕色的',                  '{KET}', '{Colours}', null, false, 3, 'active'),
('brush',           'n',      '刷子；刷',                '{KET}', '{}', null, false, 5, 'active'),
('build',           'v',      '建造',                    '{KET}', '{}', null, false, 3, 'active'),
('building',        'n',      '建築物',                  '{KET}', '{Places: Buildings}', null, false, 5, 'active'),
('burger',          'n',      '漢堡',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('bus',             'n',      '公車',                    '{KET}', '{Travel and Transport}', null, false, 5, 'active'),
('business',        'n',      '生意、公司',              '{KET}', '{Work and Jobs}', null, false, 2, 'active'),
('businessman',     'n',      '商人（男）',              '{KET}', '{Work and Jobs}', null, false, 4, 'active'),
('businesswoman',   'n',      '商人（女）',              '{KET}', '{Work and Jobs}', null, false, 4, 'active'),
('business person', 'n',      '商務人士',                '{KET}', '{Work and Jobs}', null, false, 4, 'active'),
('bus station',     'n',      '公車總站',                '{KET}', '{Places: Town and City}', null, false, 5, 'active'),
('bus stop',        'n',      '公車站牌',                '{KET}', '{Places: Town and City}', null, false, 5, 'active'),
('busy',            'adj',    '忙碌的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('but',             'conj',   '但是',                    '{KET}', '{}', null, false, 1, 'active'),
('butter',          'n',      '奶油',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('butterfly',       'n',      '蝴蝶',                    '{KET}', '{}', null, false, 5, 'active'),
('buy',             'v',      '買',                      '{KET}', '{Shopping}', null, false, 2, 'active'),
('by',              'prep',   '藉由、在……旁',            '{KET}', '{}', null, false, 1, 'active'),
('by accident',     'prep',   '意外地、不小心',          '{KET}', '{}', null, false, 1, 'active'),
('by the way',      'prep',   '順帶一提',                '{KET}', '{}', null, false, 1, 'active'),
('by post',         'prep',   '以郵寄方式',              '{KET}', '{Communication and Technology}', null, false, 2, 'active'),
('bye',             'exclam', '再見',                    '{KET}', '{}', null, false, 1, 'active'),

-- ---------- C ----------
('cabinet',         'n',      '櫥櫃',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('cafe',            'n',      '咖啡廳',                  '{KET}', '{Places: Buildings, Services}', null, false, 5, 'active'),
('cafeteria',       'n',      '自助餐廳',                '{KET}', '{Places: Buildings, Services}', null, false, 5, 'active'),
('cake',            'n',      '蛋糕',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('calendar',        'n',      '日曆',                    '{KET}', '{Time}', null, false, 5, 'active'),
('call',            'v',      '打電話；稱呼',            '{KET}', '{Communication and Technology}', 'I will call again later. / He is called John.', false, 2, 'active'),
('camel',           'n',      '駱駝',                    '{KET}', '{}', null, false, 5, 'active'),
('camera',          'n',      '相機',                    '{KET}', '{Appliances, Communication and Technology}', null, false, 5, 'active'),
('camp',            'v',      '露營',                    '{KET}', '{Hobbies and Leisure}', null, false, 3, 'active'),
('camping',         'n',      '露營',                    '{KET}', '{Hobbies and Leisure}', null, false, 3, 'active'),
('campsite',        'n',      '露營區',                  '{KET}', '{Hobbies and Leisure, Places: Countryside}', null, false, 5, 'active'),
('cap',             'n',      '鴨舌帽',                  '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('capital',         'n',      '首都；大寫字母',          '{KET}', '{}', null, false, 3, 'active'),
('can',             'mv',     '能夠、可以',              '{KET}', '{}', 'I can ride a bike.（能力／請求／許可／可能）', false, 1, 'active'),
('candy',           'n',      '糖果（美式）',            '{KET}', '{Food and Drink}', 'Am Eng；Br Eng 為 sweets', false, 5, 'active'),
('cannot',          'mv',     '不能',                    '{KET}', '{}', null, false, 1, 'active'),
('car',             'n',      '汽車',                    '{KET}', '{Travel and Transport}', null, false, 5, 'active'),
('card',            'n',      '卡片',                    '{KET}', '{Documents and Texts}', 'birthday card / credit card / card game', false, 5, 'active'),
('career',          'n',      '職業生涯',                '{KET}', '{}', null, false, 1, 'active'),
('careful',         'adj',    '小心的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', 'Be careful!', false, 1, 'active'),
('carefully',       'adv',    '小心地',                  '{KET}', '{}', null, false, 1, 'active'),
('car park',        'n',      '停車場（英式）',          '{KET}', '{Places: Town and City}', 'Br Eng；Am Eng 為 parking lot', false, 5, 'active'),
('carpet',          'n',      '地毯',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('carrot',          'n',      '紅蘿蔔',                  '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('carry',           'v',      '攜帶、搬運',              '{KET}', '{}', null, false, 3, 'active'),
('cartoon',         'n',      '卡通',                    '{KET}', '{Documents and Texts, Entertainment and Media}', null, false, 4, 'active'),
('case',            'n',      '箱子、盒子',              '{KET}', '{Travel and Transport}', null, false, 4, 'active'),
('cash',            'n',      '現金',                    '{KET}', '{Shopping}', null, false, 4, 'active'),
('castle',          'n',      '城堡',                    '{KET}', '{Places: Buildings}', null, false, 5, 'active'),
('cat',             'n',      '貓',                      '{KET}', '{}', null, false, 5, 'active'),
('catch',           'v',      '接住；趕上',              '{KET}', '{Sport}', null, false, 3, 'active'),
('CD',              'n',      '光碟',                    '{KET}', '{Appliances, Communication and Technology}', null, false, 5, 'active'),
('CD player',       'n',      '光碟播放器',              '{KET}', '{Appliances}', null, false, 5, 'active'),
('ceiling',         'n',      '天花板',                  '{KET}', '{House and Home}', null, false, 5, 'active'),
('cell phone',      'n',      '手機（美式）',            '{KET}', '{Appliances, Communication and Technology}', null, false, 5, 'active'),
('celebrate',       'v',      '慶祝',                    '{KET}', '{}', null, false, 2, 'active'),
('celebrity',       'n',      '名人',                    '{KET}', '{}', null, false, 3, 'active'),
('cent',            'n',      '分（貨幣單位）',          '{KET}', '{Shopping}', null, false, 3, 'active'),
('centre',          'n',      '中心（英式）',            '{KET}', '{}', 'Br Eng；Am Eng 為 center', false, 3, 'active'),
('center',          'n',      '中心（美式）',            '{KET}', '{}', 'Am Eng；Br Eng 為 centre', false, 3, 'active'),
('centimetre',      'n',      '公分（英式）',            '{KET}', '{Measurements}', 'Br Eng；Am Eng 為 centimeter', false, 3, 'active'),
('centimeter',      'n',      '公分（美式）',            '{KET}', '{Measurements}', 'Am Eng；Br Eng 為 centimetre', false, 3, 'active'),
('century',         'n',      '世紀',                    '{KET}', '{}', null, false, 2, 'active'),
('cereal',          'n',      '穀片',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('certainly',       'adv',    '當然、必定',              '{KET}', '{}', null, false, 1, 'active'),
('chain',           'n',      '鏈子',                    '{KET}', '{Clothes and Accessories}', 'She wore a gold chain.', false, 5, 'active'),
('chair',           'n',      '椅子',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('change',          'v',      '改變；零錢',              '{KET}', '{Shopping}', null, false, 2, 'active'),
('channel',         'n',      '頻道',                    '{KET}', '{}', null, false, 3, 'active'),
('character',       'n',      '角色',                    '{KET}', '{}', 'He was my favourite character in the film.', false, 3, 'active'),
('chat',            'n',      '聊天',                    '{KET}', '{Communication and Technology}', null, false, 2, 'active'),
('chatroom',        'n',      '聊天室',                  '{KET}', '{Communication and Technology}', null, false, 3, 'active'),
('cheap',           'adj',    '便宜的',                  '{KET}', '{Shopping}', null, false, 2, 'active'),
('check',           'v',      '檢查、確認',              '{KET}', '{Health, Medicine and Exercise}', null, false, 2, 'active'),
('cheese',          'n',      '起司',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('chef',            'n',      '主廚',                    '{KET}', '{Food and Drink}', null, false, 4, 'active'),
('chemist',         'n',      '藥局（英式）',            '{KET}', '{Work and Jobs}', 'Br Eng；Am Eng 為 drugstore', false, 5, 'active'),
('chemistry',       'n',      '化學',                    '{KET}', '{Education}', null, false, 2, 'active'),
('cheque',          'n',      '支票',                    '{KET}', '{Shopping}', null, false, 4, 'active'),
('chess',           'n',      '西洋棋',                  '{KET}', '{Entertainment and Media}', null, false, 4, 'active'),
('chicken',         'n',      '雞、雞肉',                '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('child',           'n',      '小孩',                    '{KET}', '{Family and Friends}', null, false, 5, 'active'),
('chilli',          'n',      '辣椒',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('chips',           'n',      '薯條（英式）',            '{KET}', '{Food and Drink}', 'Br Eng；Am Eng 為 French fries', false, 5, 'active'),
('chocolate',       'n',      '巧克力',                  '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('choose',          'v',      '選擇',                    '{KET}', '{}', null, false, 1, 'active'),
('cinema',          'n',      '電影院（英式）',          '{KET}', '{Places: Buildings, Services}', 'Br Eng；Am Eng 為 movie theater', false, 5, 'active'),
('circle',          'n',      '圓圈',                    '{KET}', '{}', null, false, 4, 'active'),
('circus',          'n',      '馬戲團',                  '{KET}', '{}', null, false, 5, 'active'),
('city',            'n',      '城市',                    '{KET}', '{}', null, false, 4, 'active'),
('city centre',     'n',      '市中心',                  '{KET}', '{Places: Town and City}', null, false, 4, 'active'),
('class',           'n',      '課；班級',                '{KET}', '{Education}', 'a language class / a first-class ticket', false, 3, 'active'),
('classical',       'adj',    '古典的',                  '{KET}', '{Entertainment and Media}', 'classical music', false, 2, 'active'),
('classmate',       'n',      '同班同學',                '{KET}', '{Education}', null, false, 4, 'active'),
('classroom',       'n',      '教室',                    '{KET}', '{Education}', null, false, 5, 'active'),
('clean',           'adj',    '乾淨的；打掃',            '{KET}', '{Health, Medicine and Exercise}', null, false, 2, 'active'),
('cleaner',         'n',      '清潔人員',                '{KET}', '{Work and Jobs}', null, false, 4, 'active'),
('clear',           'adj',    '清楚的',                  '{KET}', '{Personal Feelings, Opinions and Experiences}', 'It is not clear to me.', false, 1, 'active'),
('clearly',         'adv',    '清楚地',                  '{KET}', '{}', null, false, 1, 'active'),
('clever',          'adj',    '聰明的',                  '{KET}', '{Education, Personal Feelings, Opinions and Experiences}', null, false, 1, 'active'),
('click',           'v',      '點擊',                    '{KET}', '{Communication and Technology}', 'Click here to go to our website.', false, 2, 'active'),
('climb',           'v',      '攀爬',                    '{KET}', '{Sport}', null, false, 3, 'active'),
('climbing',        'n',      '攀岩、登山',              '{KET}', '{}', null, false, 3, 'active'),
('clock',           'n',      '時鐘',                    '{KET}', '{Appliances, House and Home, Time}', null, false, 5, 'active'),
('close',           'v',      '關閉',                    '{KET}', '{Shopping}', null, false, 2, 'active'),
('close to',        'prep',   '靠近',                    '{KET}', '{}', null, false, 2, 'active'),
('closed',          'adj',    '關閉的',                  '{KET}', '{Shopping}', null, false, 2, 'active'),
('closet',          'n',      '衣櫃（美式）',            '{KET}', '{House and Home}', null, false, 5, 'active'),
('clothes',         'n',      '衣服',                    '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('cloud',           'n',      '雲',                      '{KET}', '{Weather}', null, false, 4, 'active'),
('cloudy',          'adj',    '多雲的',                  '{KET}', '{Weather}', null, false, 3, 'active'),
('clown',           'n',      '小丑',                    '{KET}', '{}', null, false, 5, 'active'),
('club',            'n',      '社團、俱樂部',            '{KET}', '{Hobbies and Leisure, Sport}', 'to join a club', false, 3, 'active'),
('coach',           'n',      '教練；長途巴士',          '{KET}', '{Sport, Work and Jobs}', 'a tennis coach / a coach trip', false, 4, 'active'),
('coat',            'n',      '外套',                    '{KET}', '{Clothes and Accessories}', null, false, 5, 'active'),
('coast',           'n',      '海岸',                    '{KET}', '{}', null, false, 4, 'active'),
('coffee',          'n',      '咖啡',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('cola',            'n',      '可樂',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('cold',            'adj',    '冷的；感冒',              '{KET}', '{Weather, Health, Medicine and Exercise}', null, false, 2, 'active'),
('colleague',       'n',      '同事',                    '{KET}', '{}', null, false, 4, 'active'),
('collect',         'v',      '收集',                    '{KET}', '{Hobbies and Leisure}', null, false, 2, 'active'),
('college',         'n',      '學院、大專',              '{KET}', '{Education, Places: Buildings}', null, false, 4, 'active'),
('colour',          'n',      '顏色（英式）',            '{KET}', '{}', 'Br Eng；Am Eng 為 color', false, 3, 'active'),
('color',           'n',      '顏色（美式）',            '{KET}', '{}', 'Am Eng；Br Eng 為 colour', false, 3, 'active'),
('comb',            'n',      '梳子',                    '{KET}', '{Health, Medicine and Exercise}', null, false, 5, 'active'),
('come',            'v',      '來',                      '{KET}', '{}', null, false, 2, 'active'),
('come back',       'phr v',  '回來',                    '{KET}', '{}', 'We came back from our holiday yesterday.', true, 2, 'active'),
('comedy',          'n',      '喜劇',                    '{KET}', '{}', null, false, 3, 'active'),
('comfortable',     'adj',    '舒服的',                  '{KET}', '{}', null, false, 2, 'active'),
('comic',           'n',      '漫畫',                    '{KET}', '{Documents and Texts}', null, false, 5, 'active'),
('company',         'n',      '公司',                    '{KET}', '{Work and Jobs}', 'What is the name of your company?', false, 3, 'active'),
('competition',     'n',      '比賽、競賽',              '{KET}', '{Entertainment and Media, Sport}', null, false, 3, 'active'),
('complete',        'v',      '完成',                    '{KET}', '{}', null, false, 1, 'active'),
('computer',        'n',      '電腦',                    '{KET}', '{Appliances, Communication and Technology, Work and Jobs}', null, false, 5, 'active'),
('concert',         'n',      '音樂會',                  '{KET}', '{Entertainment and Media}', null, false, 4, 'active'),
('congratulations', 'exclam', '恭喜',                    '{KET}', '{}', null, false, 1, 'active'),
('contact',         'v',      '聯絡',                    '{KET}', '{}', null, false, 2, 'active'),
('continue',        'v',      '繼續',                    '{KET}', '{}', null, false, 1, 'active'),
('conversation',    'n',      '對話',                    '{KET}', '{Communication and Technology}', null, false, 2, 'active'),
('cook',            'v',      '烹飪；廚師',              '{KET}', '{Food and Drink, Work and Jobs}', null, false, 3, 'active'),
('cooker',          'n',      '爐具',                    '{KET}', '{Appliances, Food and Drink, House and Home}', null, false, 5, 'active'),
('cookie',          'n',      '餅乾（美式）',            '{KET}', '{Food and Drink}', 'Am Eng；Br Eng 為 biscuit', false, 5, 'active'),
('cooking',         'n',      '烹飪',                    '{KET}', '{}', null, false, 3, 'active'),
('cool',            'adj',    '酷的、涼的',              '{KET}', '{Personal Feelings, Opinions and Experiences}', 'That is a cool bike!', false, 2, 'active'),
('copy',            'v',      '複製、抄寫',              '{KET}', '{}', null, false, 2, 'active'),
('corner',          'n',      '角落、轉角',              '{KET}', '{Places: Town and City}', 'the corner of the street', false, 3, 'active'),
('correct',         'adj',    '正確的',                  '{KET}', '{}', null, false, 1, 'active'),
('cost',            'v',      '花費',                    '{KET}', '{Shopping}', null, false, 2, 'active'),
('costume',         'n',      '服裝；泳衣',              '{KET}', '{Clothes and Accessories}', 'I forgot my swimming costume.', false, 5, 'active'),
('could',           'mv',     '可以、能夠（過去或委婉）', '{KET}', '{}', 'Could you lend me some money?', false, 1, 'active'),
('country',         'n',      '國家；鄉間',              '{KET}', '{The Natural World}', null, false, 3, 'active'),
('countryside',     'n',      '鄉間、郊外',              '{KET}', '{Places: Countryside, The Natural World}', null, false, 4, 'active'),
('course',          'n',      '課程；一道菜',            '{KET}', '{Education}', 'a university course / a main course', false, 2, 'active'),
('court',           'n',      '球場',                    '{KET}', '{}', 'a tennis court', false, 4, 'active'),
('cousin',          'n',      '堂／表兄弟姊妹',          '{KET}', '{Family and Friends}', null, false, 4, 'active'),
('cover',           'v',      '覆蓋；封面',              '{KET}', '{}', 'I had to cover my eyes. / the book cover', false, 3, 'active'),
('cow',             'n',      '母牛',                    '{KET}', '{}', null, false, 5, 'active'),
('cream',           'n',      '奶油；乳白色',            '{KET}', '{Food and Drink}', 'strawberries and cream / a cream T-shirt', false, 4, 'active'),
('creature',        'n',      '生物',                    '{KET}', '{}', null, false, 3, 'active'),
('credit card',     'n',      '信用卡',                  '{KET}', '{Shopping}', null, false, 5, 'active'),
('cricket',         'n',      '板球',                    '{KET}', '{Sport}', null, false, 4, 'active'),
('crocodile',       'n',      '鱷魚',                    '{KET}', '{}', null, false, 5, 'active'),
('cross',           'v',      '穿越',                    '{KET}', '{}', 'Do not cross the road here!', false, 3, 'active'),
('crossing',        'n',      '行人穿越道',              '{KET}', '{}', 'Use the crossing to cross the street.', false, 4, 'active'),
('crowd',           'n',      '人群',                    '{KET}', '{}', null, false, 4, 'active'),
('crowded',         'adj',    '擁擠的',                  '{KET}', '{}', null, false, 2, 'active'),
('cry',             'v',      '哭',                      '{KET}', '{}', 'The baby is crying.', false, 3, 'active'),
('cup',             'n',      '杯子',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('cupboard',        'n',      '櫥櫃',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('curry',           'n',      '咖哩',                    '{KET}', '{Food and Drink}', null, false, 5, 'active'),
('curtain',         'n',      '窗簾',                    '{KET}', '{House and Home}', null, false, 5, 'active'),
('customer',        'n',      '顧客',                    '{KET}', '{Shopping, Work and Jobs}', null, false, 4, 'active'),
('cut',             'v',      '切、剪',                  '{KET}', '{Food and Drink, Health, Medicine and Exercise}', null, false, 3, 'active'),
('cycle',           'v',      '騎腳踏車',                '{KET}', '{}', null, false, 3, 'active'),
('cycling',         'n',      '騎腳踏車',                '{KET}', '{Hobbies and Leisure, Sport}', null, false, 3, 'active')
on conflict (headword) do nothing;


-- ============================================================
-- 驗收：預期本批 271 筆，累計 368 筆
-- ============================================================
select
  count(*) filter (where headword ~* '^[bc]')                  as 本批筆數,
  count(*)                                                     as 累計筆數,
  count(*) filter (where zh is null or trim(zh) = '')          as zh為空,
  count(*) filter (where status is distinct from 'active')     as 狀態異常
from words;
